### ISSUE TITLE
Daily Scrum

### ISSUE THREAD

**Issue by pimcookcu** [pimcookcu/oosd-asdf#2]
> 1.What did you do yesterday?
> 2.What will you do today?
> 3.Are there any obstacles in your way?

10 March 2016

**Comment by llllollll** [comment]
1. preview RestaurantQueuing code.
2. review RestaurantQueuing code.
3. I am forget my github password and account.

**Comment by pimcookcu** [comment]
1. Yesterday I upload the code in repository and learn how github desktop work.
2. Today I will review the code. (Just to see the whole picture ). and review the way netbeans working since i have not been using it for so long.
3. I got confuse while trying to use github desktop. This is a new thing for me . Take very long time just to push the code in.

**Comment by kunakorncsc319** [comment]
1.yesterday day I've been find the library of this project and find out the way how to upload the project
2. today  I reviewed the code of each class 
3. I plan to understand the code and begin try to think how to begin of this project

**Comment by Reeniizzmich** [comment]
1.Yesterday I try to learn how used git hub and installing in the desktop work.
2.Today I reviewed how to used  netbeans working and find the  free clone code to implement the project .

3.In term of java programming obstacles for me but I try to improve this knowledge.
