### ISSUE TITLE
Daily Scrum #2 11 March 

### ISSUE THREAD

**Issue by pimcookcu** [pimcookcu/oosd-asdf#4]
1. what did you do today?
2. what are you going to do tomorrow?
3. is anything in your ways?

**Comment by kunakorncsc319** [comment]
1. Today  i know about what is mvc how to write code as mvc 
2. Tommorow i will review my code but specipic class or method  look at inside
   3.at this moment there arent  obstruction

**Comment by Reeniizzmich** [comment]
1.I studying mvc overwiew and try to lern how to use netbean.
2.I will used netbean witht our code to implement.

3.the code of our project

**Comment by pimcookcu** [comment]
1.review some of the code and get to know the mvc concept. Look at some mvc example code 
2.study more mvc code 
3.nothing really on my way but the mvc need a lot of understanding.

**Comment by llllollll** [comment]
1. learn about  MVC, what is MVC, how to write MVC
2. try to find more example about MVC
3. confuse about MVC
