### ISSUE TITLE
daily scrum day #3 14 March 2016

### ISSUE THREAD

**Issue by kunakorncsc319** [pimcookcu/oosd-asdf#5]
1.what did you do today?
2.what are you going to do tomorrow?
3.is there any problem?

**Comment by pimcookcu** [comment]
1.Study MVC design
2. Ask someone to teach about MVC and how to apply to this project.
3.Do not understand the mvc model.

**Comment by llllollll** [comment]
1. Learn about MVC
2. Try to understand more about MVC
3. still confused about MVC

**Comment by Reeniizzmich** [comment]
1.Learned about MVC design
2.Find the example of mvc and  try to understand mvc
3.  Misunderstand some frameork

**Comment by kunakorncsc319** [comment]
1.study about how mbc quality of code
2.start look at code and seprate a jobs
3.have a problem about mvc
